### ISSUE TITLE
Auto-close OSD on resume

### ISSUE THREAD

**Issue by GulGreg** [Nessus85100/skin.bello.9#20]
When user resume the media, it could be helpful to close automatically the OSD after a short delay customizable in setting.
I will avoid the need to press the back button on the remote.

e.g.
I'm playing a movie
I put it in pause
I resume the movie
→ after x seconds, the osd disappears.

**Comment by Nessus85100** [comment]
It depends how you pause the video. If you press ENTER on your K/B or OK in your remote that will open OSD controls so you need to close them again. If you press the space bar or the PAUSE button on your remote, the OSD controls will not open.

Is the same behavior like Estuary and the most of the skins.
